# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform AdGuard Home installation tasks
  when: adguard_home_enabled | bool
  tags:
    - setup-all
    - setup-adguard-home
    - install-all
    - install-adguard-home
  block:
    - name: Validate AdGuard Home configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install AdGuard Home
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform AdGuard Home uninstallation tasks
  when: not adguard_home_enabled | bool
  tags:
    - setup-all
    - setup-adguard-home
  block:
    - name: Uninstall AdGuard Home
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
