# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of AdGuard Home systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ adguard_home_identifier }}.service"
  register: adguard_home_service_stat

- name: Uninstall AdGuard Home systemd services and files
  when: adguard_home_service_stat.stat.exists | bool
  block:
    - name: Ensure AdGuard Home systemd service is stopped
      ansible.builtin.service:
        name: "{{ adguard_home_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure AdGuard Home systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ adguard_home_identifier }}.service"
        state: absent

    - name: Ensure AdGuard Home container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ adguard_home_container_network }}"
        state: absent

    - name: Ensure AdGuard Home container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ adguard_home_container_network }}
      register: network_deletion_result
      changed_when: adguard_home_container_network in network_deletion_result.stdout

    - name: Ensure AdGuard Home path does not exist
      ansible.builtin.file:
        path: "{{ adguard_home_base_path }}"
        state: absent
