# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required AdGuard Home settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - adguard_home_identifier
    - adguard_home_uid
    - adguard_home_gid
    - adguard_home_hostname
    - adguard_home_path_prefix
    - adguard_home_container_network

- name: Run if Traefik is enabled
  when: adguard_home_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required AdGuard Home Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - adguard_home_container_labels_traefik_hostname
        - adguard_home_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `adguard_home_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if adguard_home_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          adguard_home_container_labels_traefik_path_prefix (`{{ adguard_home_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/adguard-home`).
      when: "adguard_home_container_labels_traefik_path_prefix != '/' and adguard_home_container_labels_traefik_path_prefix[-1] == '/'"
