# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "adguard_home_http_header_content_permission_policy", "new": "adguard_home_http_header_permissions_policy" }

- name: Fail if required AdGuard Home settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - adguard_home_identifier
    - adguard_home_uid
    - adguard_home_gid
    - adguard_home_hostname
    - adguard_home_path_prefix
    - adguard_home_container_network

- name: Run if Traefik is enabled
  when: adguard_home_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for AdGuard Home are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - adguard_home_container_labels_traefik_hostname
        - adguard_home_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `adguard_home_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if adguard_home_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          adguard_home_container_labels_traefik_path_prefix (`{{ adguard_home_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/adguard-home`).
      when: "adguard_home_container_labels_traefik_path_prefix != '/' and adguard_home_container_labels_traefik_path_prefix[-1] == '/'"
